const nodemailer = require('nodemailer');

// ─── Create Transporter ───────────────────────────────────────
const createTransporter = () => {
  return nodemailer.createTransport({
    service: process.env.EMAIL_SERVICE || 'gmail',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS
    }
  });
};

// ─── Format Items Table for Email ────────────────────────────
const buildItemsTable = (items) => {
  if (!items || items.length === 0) return '<p>No items selected.</p>';
  return `
    <table style="width:100%;border-collapse:collapse;margin:16px 0;">
      <thead>
        <tr style="background:#1a1a2e;color:white;">
          <th style="padding:10px 14px;text-align:left;border:1px solid #ddd;">#</th>
          <th style="padding:10px 14px;text-align:left;border:1px solid #ddd;">Item Name</th>
          <th style="padding:10px 14px;text-align:center;border:1px solid #ddd;">Quantity</th>
        </tr>
      </thead>
      <tbody>
        ${items.map((item, i) => `
          <tr style="background:${i % 2 === 0 ? '#f9f9f9' : '#ffffff'}">
            <td style="padding:8px 14px;border:1px solid #ddd;">${i + 1}</td>
            <td style="padding:8px 14px;border:1px solid #ddd;">${item.name}</td>
            <td style="padding:8px 14px;border:1px solid #ddd;text-align:center;">${item.quantity}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  `;
};

// ─── Send Order Email ─────────────────────────────────────────
const sendOrderEmail = async (order) => {
  const transporter = createTransporter();
  const companyName = process.env.COMPANY_NAME || 'FACTOTUM SERVICES PVT. LTD.';
  const deliveryDate = new Date(order.deliveryDate).toLocaleDateString('en-IN', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  });

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head><meta charset="UTF-8"></head>
    <body style="font-family: 'Segoe UI', Arial, sans-serif; margin:0; padding:0; background:#f0f0f0;">
      <div style="max-width:680px;margin:30px auto;background:white;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);">
        
        <!-- Header -->
        <div style="background:#1a1a2e;padding:32px 40px;text-align:center;">
          <h1 style="color:#e8c547;margin:0;font-size:22px;letter-spacing:2px;">${companyName}</h1>
          <p style="color:#a0a0b0;margin:8px 0 0;font-size:14px;">Cleaning Supplies Order Notification</p>
        </div>

        <!-- Order Badge -->
        <div style="background:#e8c547;padding:16px 40px;text-align:center;">
          <p style="margin:0;font-weight:700;color:#1a1a2e;font-size:18px;">
            NEW ORDER: ${order.orderNumber}
          </p>
        </div>

        <!-- Body -->
        <div style="padding:32px 40px;">
          
          <!-- Order Meta -->
          <table style="width:100%;margin-bottom:24px;">
            <tr>
              <td style="padding:8px 0;color:#666;font-size:14px;width:160px;">📍 <strong>Store / Address</strong></td>
              <td style="padding:8px 0;color:#1a1a2e;font-size:14px;">${order.store}</td>
            </tr>
            <tr>
              <td style="padding:8px 0;color:#666;font-size:14px;">📅 <strong>Delivery Date</strong></td>
              <td style="padding:8px 0;color:#1a1a2e;font-size:14px;">${deliveryDate}</td>
            </tr>
            <tr>
              <td style="padding:8px 0;color:#666;font-size:14px;">✍️ <strong>Requested By</strong></td>
              <td style="padding:8px 0;color:#1a1a2e;font-size:14px;">${order.signatory}</td>
            </tr>
            <tr>
              <td style="padding:8px 0;color:#666;font-size:14px;">🕐 <strong>Submitted At</strong></td>
              <td style="padding:8px 0;color:#1a1a2e;font-size:14px;">${new Date(order.createdAt).toLocaleString('en-IN')}</td>
            </tr>
          </table>

          <!-- Items -->
          <h3 style="color:#1a1a2e;border-bottom:2px solid #e8c547;padding-bottom:8px;">
            Order Items (${order.items.length} items)
          </h3>
          ${buildItemsTable(order.items)}

          ${order.otherItems ? `
            <div style="background:#fff8e1;border-left:4px solid #e8c547;padding:16px;border-radius:4px;margin-top:16px;">
              <strong style="color:#1a1a2e;">📝 Additional Items / Notes:</strong>
              <p style="margin:8px 0 0;color:#555;">${order.otherItems}</p>
            </div>
          ` : ''}

        </div>

        <!-- Footer -->
        <div style="background:#f5f5f5;padding:20px 40px;text-align:center;border-top:1px solid #e0e0e0;">
          <p style="margin:0;color:#999;font-size:12px;">
            This email was automatically generated by the ${companyName} Order Management System.<br>
            Please do not reply to this email.
          </p>
        </div>
      </div>
    </body>
    </html>
  `;

  const mailOptions = {
    from: `"${companyName} Orders" <${process.env.EMAIL_USER}>`,
    to: process.env.EMAIL_RECIPIENT,
    subject: `📦 New Order ${order.orderNumber} – ${order.store}`,
    html: htmlContent
  };

  await transporter.sendMail(mailOptions);
};

module.exports = { sendOrderEmail };
